[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/server"

[functions]
  included_files = ["dist/server/**/*.mjs"]

[[redirects]]
  from = "/studio/*"
  to = "buried-fe.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200 
